/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.Reader;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
@Test void testInGson(){
    Reader reader = null;
    try {
        reader = Files.newBufferedReader(Paths.get("app/src/main/resources/recentquotes.json"));
        List<Quote> users = new Gson().fromJson(reader, new TypeToken<List<Quote>>() {}.getType());
        assertEquals("Marilyn Monroe",users.get(0).getAuthor());
        assertEquals( " “I am good, but not an angel. I do sin, but I am not the devil. I am just a small girl in a big world trying to find someone to love.” ",users.get(0).getText());
    } catch (IOException e) {
        e.printStackTrace();
    }


}
}
