/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;

import java.io.IOException;
import java.io.Reader;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;

public class App {

    public static void main(String[] args)  {
        Reader reader = null;
        try {
            reader = Files.newBufferedReader(Paths.get("app/src/main/resources/recentquotes.json"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        List<Quote> users = new Gson().fromJson(reader, new TypeToken<List<Quote>>() {}.getType());
        int random =  (int)(Math.random() * ((users.size()) + 1));
        System.out.println(users.get(random).getAuthor() + " \n" + users.get(random).getText());


    }
}
